// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: main_api.proto

package main_api

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "github.com/mwitkow/go-proto-validators"
	regexp "regexp"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

var _regex_SampleRequest_SystemCode = regexp.MustCompile(`^([ABZ])?$`)

func (this *SampleRequest) Validate() error {
	if !_regex_SampleRequest_SystemCode.MatchString(this.SystemCode) {
		return github_com_mwitkow_go_proto_validators.FieldError("SystemCode", fmt.Errorf(`value '%v' must be a string conforming to regex "^([ABZ])?$"`, this.SystemCode))
	}
	return nil
}
func (this *SampleResponse) Validate() error {
	return nil
}
