// Code generated by protoc-gen-go. DO NOT EDIT.
// source: article.proto

package article

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ArticleListRequest struct {
	SystemCode           string   `protobuf:"bytes,1,opt,name=system_code,json=systemCode,proto3" json:"system_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArticleListRequest) Reset()         { *m = ArticleListRequest{} }
func (m *ArticleListRequest) String() string { return proto.CompactTextString(m) }
func (*ArticleListRequest) ProtoMessage()    {}
func (*ArticleListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c593d380f9840a2, []int{0}
}

func (m *ArticleListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleListRequest.Unmarshal(m, b)
}
func (m *ArticleListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleListRequest.Marshal(b, m, deterministic)
}
func (m *ArticleListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleListRequest.Merge(m, src)
}
func (m *ArticleListRequest) XXX_Size() int {
	return xxx_messageInfo_ArticleListRequest.Size(m)
}
func (m *ArticleListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleListRequest proto.InternalMessageInfo

func (m *ArticleListRequest) GetSystemCode() string {
	if m != nil {
		return m.SystemCode
	}
	return ""
}

type ArticleRequest struct {
	SystemCode           string   `protobuf:"bytes,1,opt,name=system_code,json=systemCode,proto3" json:"system_code,omitempty"`
	ArticleId            string   `protobuf:"bytes,2,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArticleRequest) Reset()         { *m = ArticleRequest{} }
func (m *ArticleRequest) String() string { return proto.CompactTextString(m) }
func (*ArticleRequest) ProtoMessage()    {}
func (*ArticleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c593d380f9840a2, []int{1}
}

func (m *ArticleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleRequest.Unmarshal(m, b)
}
func (m *ArticleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleRequest.Marshal(b, m, deterministic)
}
func (m *ArticleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleRequest.Merge(m, src)
}
func (m *ArticleRequest) XXX_Size() int {
	return xxx_messageInfo_ArticleRequest.Size(m)
}
func (m *ArticleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleRequest proto.InternalMessageInfo

func (m *ArticleRequest) GetSystemCode() string {
	if m != nil {
		return m.SystemCode
	}
	return ""
}

func (m *ArticleRequest) GetArticleId() string {
	if m != nil {
		return m.ArticleId
	}
	return ""
}

type ArticleListResponse struct {
	Articles             []*ArticleResponse `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ArticleListResponse) Reset()         { *m = ArticleListResponse{} }
func (m *ArticleListResponse) String() string { return proto.CompactTextString(m) }
func (*ArticleListResponse) ProtoMessage()    {}
func (*ArticleListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c593d380f9840a2, []int{2}
}

func (m *ArticleListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleListResponse.Unmarshal(m, b)
}
func (m *ArticleListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleListResponse.Marshal(b, m, deterministic)
}
func (m *ArticleListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleListResponse.Merge(m, src)
}
func (m *ArticleListResponse) XXX_Size() int {
	return xxx_messageInfo_ArticleListResponse.Size(m)
}
func (m *ArticleListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleListResponse proto.InternalMessageInfo

func (m *ArticleListResponse) GetArticles() []*ArticleResponse {
	if m != nil {
		return m.Articles
	}
	return nil
}

type ArticleResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArticleResponse) Reset()         { *m = ArticleResponse{} }
func (m *ArticleResponse) String() string { return proto.CompactTextString(m) }
func (*ArticleResponse) ProtoMessage()    {}
func (*ArticleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c593d380f9840a2, []int{3}
}

func (m *ArticleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleResponse.Unmarshal(m, b)
}
func (m *ArticleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleResponse.Marshal(b, m, deterministic)
}
func (m *ArticleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleResponse.Merge(m, src)
}
func (m *ArticleResponse) XXX_Size() int {
	return xxx_messageInfo_ArticleResponse.Size(m)
}
func (m *ArticleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleResponse proto.InternalMessageInfo

func (m *ArticleResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ArticleResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func init() {
	proto.RegisterType((*ArticleListRequest)(nil), "article.ArticleListRequest")
	proto.RegisterType((*ArticleRequest)(nil), "article.ArticleRequest")
	proto.RegisterType((*ArticleListResponse)(nil), "article.ArticleListResponse")
	proto.RegisterType((*ArticleResponse)(nil), "article.ArticleResponse")
}

func init() { proto.RegisterFile("article.proto", fileDescriptor_5c593d380f9840a2) }

var fileDescriptor_5c593d380f9840a2 = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x2c, 0x2a, 0xc9,
	0x4c, 0xce, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0x4c, 0xb9,
	0x84, 0x1c, 0x21, 0x4c, 0x9f, 0xcc, 0xe2, 0x92, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21,
	0x79, 0x2e, 0xee, 0xe2, 0xca, 0xe2, 0x92, 0xd4, 0xdc, 0xf8, 0xe4, 0xfc, 0x94, 0x54, 0x09, 0x46,
	0x05, 0x46, 0x0d, 0xce, 0x20, 0x2e, 0x88, 0x90, 0x73, 0x7e, 0x4a, 0xaa, 0x52, 0x00, 0x17, 0x1f,
	0x54, 0x1b, 0xb1, 0x5a, 0x84, 0x64, 0xb9, 0xb8, 0xa0, 0x96, 0xc6, 0x67, 0xa6, 0x48, 0x30, 0x81,
	0xe5, 0x39, 0xa1, 0x22, 0x9e, 0x29, 0x4a, 0xde, 0x5c, 0xc2, 0x28, 0x0e, 0x29, 0x2e, 0xc8, 0xcf,
	0x2b, 0x4e, 0x15, 0x32, 0xe1, 0xe2, 0x80, 0xaa, 0x29, 0x96, 0x60, 0x54, 0x60, 0xd6, 0xe0, 0x36,
	0x92, 0xd0, 0x83, 0x79, 0x05, 0xee, 0x02, 0x88, 0xda, 0x20, 0xb8, 0x4a, 0x25, 0x7b, 0x2e, 0x7e,
	0x34, 0x49, 0x21, 0x31, 0x2e, 0xb6, 0xe2, 0x92, 0xc4, 0x92, 0xd2, 0x62, 0xb0, 0xd3, 0x58, 0x83,
	0xa0, 0x3c, 0x21, 0x11, 0x2e, 0xd6, 0x92, 0xcc, 0x92, 0x9c, 0x54, 0xa8, 0x8b, 0x20, 0x1c, 0xa3,
	0xd9, 0x8c, 0x5c, 0xec, 0x50, 0x13, 0x84, 0x7c, 0xb9, 0xf8, 0xdc, 0x53, 0x4b, 0x90, 0x1c, 0x27,
	0x24, 0x8d, 0xee, 0x04, 0xa4, 0xb0, 0x93, 0x92, 0xc1, 0x2e, 0x09, 0x71, 0x86, 0x12, 0x83, 0x90,
	0x23, 0x17, 0x17, 0xc2, 0x38, 0x21, 0x71, 0x4c, 0xdf, 0x40, 0x8c, 0xc1, 0xe9, 0x4d, 0x25, 0x86,
	0x24, 0x36, 0x70, 0x24, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x7b, 0x75, 0x8d, 0x3b, 0xd5,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ArticleClient is the client API for Article service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ArticleClient interface {
	GetArticleList(ctx context.Context, in *ArticleListRequest, opts ...grpc.CallOption) (*ArticleListResponse, error)
	GetArticle(ctx context.Context, in *ArticleRequest, opts ...grpc.CallOption) (*ArticleResponse, error)
}

type articleClient struct {
	cc grpc.ClientConnInterface
}

func NewArticleClient(cc grpc.ClientConnInterface) ArticleClient {
	return &articleClient{cc}
}

func (c *articleClient) GetArticleList(ctx context.Context, in *ArticleListRequest, opts ...grpc.CallOption) (*ArticleListResponse, error) {
	out := new(ArticleListResponse)
	err := c.cc.Invoke(ctx, "/article.Article/GetArticleList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleClient) GetArticle(ctx context.Context, in *ArticleRequest, opts ...grpc.CallOption) (*ArticleResponse, error) {
	out := new(ArticleResponse)
	err := c.cc.Invoke(ctx, "/article.Article/GetArticle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArticleServer is the server API for Article service.
type ArticleServer interface {
	GetArticleList(context.Context, *ArticleListRequest) (*ArticleListResponse, error)
	GetArticle(context.Context, *ArticleRequest) (*ArticleResponse, error)
}

// UnimplementedArticleServer can be embedded to have forward compatible implementations.
type UnimplementedArticleServer struct {
}

func (*UnimplementedArticleServer) GetArticleList(ctx context.Context, req *ArticleListRequest) (*ArticleListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetArticleList not implemented")
}
func (*UnimplementedArticleServer) GetArticle(ctx context.Context, req *ArticleRequest) (*ArticleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetArticle not implemented")
}

func RegisterArticleServer(s *grpc.Server, srv ArticleServer) {
	s.RegisterService(&_Article_serviceDesc, srv)
}

func _Article_GetArticleList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArticleListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServer).GetArticleList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/article.Article/GetArticleList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServer).GetArticleList(ctx, req.(*ArticleListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Article_GetArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServer).GetArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/article.Article/GetArticle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServer).GetArticle(ctx, req.(*ArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Article_serviceDesc = grpc.ServiceDesc{
	ServiceName: "article.Article",
	HandlerType: (*ArticleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetArticleList",
			Handler:    _Article_GetArticleList_Handler,
		},
		{
			MethodName: "GetArticle",
			Handler:    _Article_GetArticle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "article.proto",
}
