settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: dev-compass-bff
  path: /go/app
  commands:
    install:
      status: true
      method: go build -o app
    run:
      status: true
      method: ./app
  watcher:
    extensions:
    - go
    paths:
    - /
    ignore:
      paths:
      - .git
      - .realize
      - vendor
