// Code generated by protoc-gen-go. DO NOT EDIT.
// source: popularity.proto

package popularity

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PopularityListRequest struct {
	SystemCode           string   `protobuf:"bytes,1,opt,name=system_code,json=systemCode,proto3" json:"system_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PopularityListRequest) Reset()         { *m = PopularityListRequest{} }
func (m *PopularityListRequest) String() string { return proto.CompactTextString(m) }
func (*PopularityListRequest) ProtoMessage()    {}
func (*PopularityListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b499e948ab229f03, []int{0}
}

func (m *PopularityListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PopularityListRequest.Unmarshal(m, b)
}
func (m *PopularityListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PopularityListRequest.Marshal(b, m, deterministic)
}
func (m *PopularityListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PopularityListRequest.Merge(m, src)
}
func (m *PopularityListRequest) XXX_Size() int {
	return xxx_messageInfo_PopularityListRequest.Size(m)
}
func (m *PopularityListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PopularityListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PopularityListRequest proto.InternalMessageInfo

func (m *PopularityListRequest) GetSystemCode() string {
	if m != nil {
		return m.SystemCode
	}
	return ""
}

type PopularityRequest struct {
	SystemCode           string   `protobuf:"bytes,1,opt,name=system_code,json=systemCode,proto3" json:"system_code,omitempty"`
	PopularityId         string   `protobuf:"bytes,2,opt,name=popularity_id,json=popularityId,proto3" json:"popularity_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PopularityRequest) Reset()         { *m = PopularityRequest{} }
func (m *PopularityRequest) String() string { return proto.CompactTextString(m) }
func (*PopularityRequest) ProtoMessage()    {}
func (*PopularityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b499e948ab229f03, []int{1}
}

func (m *PopularityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PopularityRequest.Unmarshal(m, b)
}
func (m *PopularityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PopularityRequest.Marshal(b, m, deterministic)
}
func (m *PopularityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PopularityRequest.Merge(m, src)
}
func (m *PopularityRequest) XXX_Size() int {
	return xxx_messageInfo_PopularityRequest.Size(m)
}
func (m *PopularityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PopularityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PopularityRequest proto.InternalMessageInfo

func (m *PopularityRequest) GetSystemCode() string {
	if m != nil {
		return m.SystemCode
	}
	return ""
}

func (m *PopularityRequest) GetPopularityId() string {
	if m != nil {
		return m.PopularityId
	}
	return ""
}

type PopularityListResponse struct {
	Popularitys          []*PopularityResponse `protobuf:"bytes,1,rep,name=popularitys,proto3" json:"popularitys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *PopularityListResponse) Reset()         { *m = PopularityListResponse{} }
func (m *PopularityListResponse) String() string { return proto.CompactTextString(m) }
func (*PopularityListResponse) ProtoMessage()    {}
func (*PopularityListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b499e948ab229f03, []int{2}
}

func (m *PopularityListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PopularityListResponse.Unmarshal(m, b)
}
func (m *PopularityListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PopularityListResponse.Marshal(b, m, deterministic)
}
func (m *PopularityListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PopularityListResponse.Merge(m, src)
}
func (m *PopularityListResponse) XXX_Size() int {
	return xxx_messageInfo_PopularityListResponse.Size(m)
}
func (m *PopularityListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PopularityListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PopularityListResponse proto.InternalMessageInfo

func (m *PopularityListResponse) GetPopularitys() []*PopularityResponse {
	if m != nil {
		return m.Popularitys
	}
	return nil
}

type PopularityResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PopularityResponse) Reset()         { *m = PopularityResponse{} }
func (m *PopularityResponse) String() string { return proto.CompactTextString(m) }
func (*PopularityResponse) ProtoMessage()    {}
func (*PopularityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b499e948ab229f03, []int{3}
}

func (m *PopularityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PopularityResponse.Unmarshal(m, b)
}
func (m *PopularityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PopularityResponse.Marshal(b, m, deterministic)
}
func (m *PopularityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PopularityResponse.Merge(m, src)
}
func (m *PopularityResponse) XXX_Size() int {
	return xxx_messageInfo_PopularityResponse.Size(m)
}
func (m *PopularityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PopularityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PopularityResponse proto.InternalMessageInfo

func (m *PopularityResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *PopularityResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func init() {
	proto.RegisterType((*PopularityListRequest)(nil), "popularity.PopularityListRequest")
	proto.RegisterType((*PopularityRequest)(nil), "popularity.PopularityRequest")
	proto.RegisterType((*PopularityListResponse)(nil), "popularity.PopularityListResponse")
	proto.RegisterType((*PopularityResponse)(nil), "popularity.PopularityResponse")
}

func init() { proto.RegisterFile("popularity.proto", fileDescriptor_b499e948ab229f03) }

var fileDescriptor_b499e948ab229f03 = []byte{
	// 247 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0xc8, 0x2f, 0x28,
	0xcd, 0x49, 0x2c, 0xca, 0x2c, 0xa9, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x42, 0x88,
	0x28, 0x59, 0x70, 0x89, 0x06, 0xc0, 0x79, 0x3e, 0x99, 0xc5, 0x25, 0x41, 0xa9, 0x85, 0xa5, 0xa9,
	0xc5, 0x25, 0x42, 0xf2, 0x5c, 0xdc, 0xc5, 0x95, 0xc5, 0x25, 0xa9, 0xb9, 0xf1, 0xc9, 0xf9, 0x29,
	0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x5c, 0x10, 0x21, 0xe7, 0xfc, 0x94, 0x54, 0xa5,
	0x48, 0x2e, 0x41, 0x84, 0x4e, 0x62, 0x75, 0x09, 0x29, 0x73, 0xf1, 0x22, 0x6c, 0x8f, 0xcf, 0x4c,
	0x91, 0x60, 0x02, 0x2b, 0xe1, 0x41, 0x08, 0x7a, 0xa6, 0x28, 0x45, 0x71, 0x89, 0xa1, 0x3b, 0xaa,
	0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0xc8, 0x81, 0x8b, 0x1b, 0xa1, 0xb2, 0x58, 0x82, 0x51, 0x81,
	0x59, 0x83, 0xdb, 0x48, 0x4e, 0x0f, 0xc9, 0x8b, 0xc8, 0x6e, 0x82, 0x68, 0x0a, 0x42, 0xd6, 0xa2,
	0xe4, 0xc4, 0x25, 0x84, 0xa9, 0x44, 0x48, 0x8c, 0x8b, 0xad, 0xb8, 0x24, 0xb1, 0xa4, 0xb4, 0x18,
	0xec, 0x64, 0xd6, 0x20, 0x28, 0x4f, 0x48, 0x84, 0x8b, 0xb5, 0x24, 0xb3, 0x24, 0x27, 0x15, 0xea,
	0x4c, 0x08, 0xc7, 0x68, 0x0f, 0x23, 0x17, 0x17, 0xc2, 0x10, 0xa1, 0x18, 0x2e, 0x41, 0xf7, 0xd4,
	0x12, 0x54, 0x17, 0x0b, 0x29, 0x62, 0x77, 0x14, 0x52, 0x10, 0x4b, 0x29, 0xe1, 0x53, 0x02, 0x71,
	0x98, 0x12, 0x83, 0x50, 0x00, 0x17, 0x2f, 0x8a, 0xe9, 0x42, 0xb2, 0xb8, 0xbc, 0x0b, 0x31, 0x95,
	0x40, 0x68, 0x28, 0x31, 0x24, 0xb1, 0x81, 0x93, 0x81, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x84,
	0x4e, 0xf5, 0xb7, 0x1a, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PopularityClient is the client API for Popularity service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PopularityClient interface {
	GetPopularityList(ctx context.Context, in *PopularityListRequest, opts ...grpc.CallOption) (*PopularityListResponse, error)
	GetPopularity(ctx context.Context, in *PopularityRequest, opts ...grpc.CallOption) (*PopularityResponse, error)
}

type popularityClient struct {
	cc grpc.ClientConnInterface
}

func NewPopularityClient(cc grpc.ClientConnInterface) PopularityClient {
	return &popularityClient{cc}
}

func (c *popularityClient) GetPopularityList(ctx context.Context, in *PopularityListRequest, opts ...grpc.CallOption) (*PopularityListResponse, error) {
	out := new(PopularityListResponse)
	err := c.cc.Invoke(ctx, "/popularity.Popularity/GetPopularityList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *popularityClient) GetPopularity(ctx context.Context, in *PopularityRequest, opts ...grpc.CallOption) (*PopularityResponse, error) {
	out := new(PopularityResponse)
	err := c.cc.Invoke(ctx, "/popularity.Popularity/GetPopularity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PopularityServer is the server API for Popularity service.
type PopularityServer interface {
	GetPopularityList(context.Context, *PopularityListRequest) (*PopularityListResponse, error)
	GetPopularity(context.Context, *PopularityRequest) (*PopularityResponse, error)
}

// UnimplementedPopularityServer can be embedded to have forward compatible implementations.
type UnimplementedPopularityServer struct {
}

func (*UnimplementedPopularityServer) GetPopularityList(ctx context.Context, req *PopularityListRequest) (*PopularityListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPopularityList not implemented")
}
func (*UnimplementedPopularityServer) GetPopularity(ctx context.Context, req *PopularityRequest) (*PopularityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPopularity not implemented")
}

func RegisterPopularityServer(s *grpc.Server, srv PopularityServer) {
	s.RegisterService(&_Popularity_serviceDesc, srv)
}

func _Popularity_GetPopularityList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PopularityListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PopularityServer).GetPopularityList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/popularity.Popularity/GetPopularityList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PopularityServer).GetPopularityList(ctx, req.(*PopularityListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Popularity_GetPopularity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PopularityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PopularityServer).GetPopularity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/popularity.Popularity/GetPopularity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PopularityServer).GetPopularity(ctx, req.(*PopularityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Popularity_serviceDesc = grpc.ServiceDesc{
	ServiceName: "popularity.Popularity",
	HandlerType: (*PopularityServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPopularityList",
			Handler:    _Popularity_GetPopularityList_Handler,
		},
		{
			MethodName: "GetPopularity",
			Handler:    _Popularity_GetPopularity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "popularity.proto",
}
